apps/devpython/urls.py
from django.urls import path, include
from django.contrib.auth.decorators import login_required

from . import views

app_name = 'devpython'

urlpatterns = [
    path('index/', login_required(views.PythonView.as_view()), name='index'),
    path('delete/<str:version>/', login_required(views.PythonDelView.as_view()), name='del'),
    path('install/', login_required(views.PythonInstallView.as_view()), name='install'),
    # path('install/download/', login_required(views.python_download), name='install_download'),
    path('install/run/', login_required(views.python_install_run),name='install_run'),
    # path('test/', login_required(views.import_iter), name='test'),
    # path('installing/<str:setup>/<str:version>/<str:website>/', views.PythonInstallingView.as_view(), name='setup'),
]

conf/urls.py
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


from appcommon import views
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('', views.CosyLoginView.as_view()),
    path('login/', views.CosyLoginView.as_view(), name='site_login'),
    path('logout/', login_required(views.CosyLayoutView.as_view()), name='site_logout'),
    path('home/', include('appcommon.urls', namespace='site_home')),
    path('system/', include('apps.system.urls', namespace='system')),
    path('devpython/', include('apps.devpython.urls', namespace='devpython')),

]

urlpatterns += staticfiles_urlpatterns()

apps/devpython/models.py
from django.db import models

# Create your models here.

apps/devpython/forms.py
from django import forms
from appcommon.forms import FormBase


class PythonInstallForm(FormBase):
    version = forms.CharField(label='可选版本', required=True)
    # website = forms.CharField(
    #     label='下载源', required=True,
    #     widget=(forms.Select(attrs={'class': 'form-control validate[required]'},
    #         choices=(('huaweicloud', '华为云'), ('python', 'Python官方(可能较慢)'))
    #     )
    #     )
    # )

apps/devpython/views.py
import os
import re
import subprocess

from django.views.generic.base import TemplateView, RedirectView
from django.views.generic.edit import FormView
from django.contrib import messages
from django.urls import reverse, reverse_lazy
from django.http import JsonResponse
from django.conf import settings

from apps.devlanguagemodule.views import DevLanguageContextMixin

from .forms import PythonInstallForm

from django.http import HttpResponse

from django.shortcuts import render


# def import_iter(request):
#     # p = subprocess.Popen('cat /opt/install01.sh', shell=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, encoding='utf-8')
#     return render(request, 'system/xterm.html', {'content': 'd'})
#

pyenv_path = '/root/.pyenv/'
pyenv_run_file = pyenv_path + '/libexec/pyenv'


class PythonContextMixin(DevLanguageContextMixin):

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['menu'] = 'python'
        return context


def get_pyenv_installed():
    """获取pyenv的python版本"""
    rootdir = pyenv_path + 'versions/'
    rlist = []
    for file in os.listdir(rootdir):
        d = os.path.join(rootdir, file)
        if not os.path.islink(d) and os.path.isdir(d):
            rlist.append(file)
    rlist.sort(key=lambda x: tuple(int(v) for v in x.split(".")))
    return_list = {}
    for v in rlist:
        env_path = os.path.join(rootdir, v, 'envs')
        return_list[v] = []
        if os.path.exists(env_path):
            for env in os.listdir(env_path):
                return_list[v].append(env)
    return return_list


def get_pyenv_py_list():
    get_run = subprocess.run(pyenv_run_file + " install --list", shell=True, capture_output=True, encoding='utf-8')
    run = get_run.stdout.strip().split('\n')
    del run[0]
    return_list = []
    installed = get_pyenv_installed()
    for v in run:
        v_t = v.strip()
        v = v_t.split('.')
        if len(v) == 3:
            if v[0].isdigit() and v[1].isdigit() and v[2].isdigit():
                if v_t not in installed:
                    if (int(v[0]) == 2 and int(v[1]) == 7 and int(v[2]) >= 10) or int(v[0]) >= 3:
                        return_list.append(v_t)
        # if re.match("^([3-9]\d|[3-9])(\.([1-9]\d|\d)){2}$", v):
        #     check = v.split('.')
        #     if v not in installed and int(check[1]) >= 3:
        #         return_list.append(v)

    return return_list


class PythonView(PythonContextMixin, TemplateView):
    template_name = 'devpython/python.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = 'Python环境'
        context['menu'] = 'python'
        context['pylist'] = get_pyenv_installed()
        return context


class PythonDelView(PythonContextMixin, RedirectView):
    url = reverse_lazy('devpython:index')

    def get(self, request, *args, **kwargs):
        run = subprocess.run(
            pyenv_run_file + ' uninstall -f ' + self.kwargs.get('version'), shell=True, capture_output=True, encoding='utf-8'
        )
        open('test.log', 'w').write('stdout:' + run.stdout + 'stderr:' + run.stderr)
        if run.stderr:
            messages.warning(self.request, run.stderr)
        return super().get(request, *args, **kwargs)


class PythonInstallView(PythonContextMixin, FormView):
    template_name = 'devpython/python_install.html'
    form_class = PythonInstallForm
    success_url = reverse_lazy('devpython:index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = '安装Python'
        context['breadcrumb'] = [
            {'title': 'python环境', 'href': reverse('devpython:index'), 'active': False},
            {'title': '安装Python', 'href': '', 'active': True},
        ]
        get_list = get_pyenv_py_list()
        context['py_version_list'] = get_list
        return context


def python_download(request):
    version = request.POST.get('version')
    website = request.POST.get('website')
    url = ''
    run_end = 0
    if website == 'python':
        url = 'https://www.python.org/ftp/python/'
    if website == 'aliyun':
        url = 'https://registry.npmmirror.com/-/binary/python/'
    if website == 'huaweicloud':
        url = 'https://mirrors.huaweicloud.com/python/{}/Python-{}.tar.xz'.format(version, version)
    if url:
        run_cmd = 'wget "{}" -O /root/.pyenv/cache/Python-{}.tar.xz'.format(url, version, version)
        run_end = subprocess.run(run_cmd, shell=True, capture_output=True, encoding='utf-8')
    return_dict = {'run_end': run_end.returncode, 'showprocess': ''}
    if run_end.stdout:
        return_dict['showprocess'] = run_end.stdout.replace('\n', '</br>')
    if run_end.stderr:
        return_dict['showprocess'] = run_end.stderr.replace('\n', '</br>')
    return JsonResponse(return_dict, safe=False)


def python_install_run(request):
    version = request.POST.get('version')
    v = version.split('.')
    if int(v[1]) >= 10:
        run_cmd = ('CPPFLAGS="$(pkg-config --cflags openssl11)" LDFLAGS="$(pkg-config --libs openssl11)" '
                   + pyenv_run_file + ' install ') + version
    else:
        run_cmd = pyenv_run_file + ' install ' + version

    run_end = subprocess.run(run_cmd, shell=True, capture_output=True, encoding='utf-8')
    return_dict = {'run_end': run_end.returncode, 'showprocess': ''}
    if run_end.stdout:
        return_dict['showprocess'] = run_end.stdout.replace('\n', '</br>')
    if run_end.stderr:
        return_dict['showprocess'] = run_end.stderr.replace('\n', '</br>')
    return JsonResponse(return_dict, safe=False)

apps/devpython/templates/devpython/python.html
{% extends 'layout/layout_main.html' %}
{% load frame_html %}
{% load frame_plugins %}

{% block css_files %}
    {% jquery_confirm 'css' %}
    {% toastr 'css' %}
{% endblock %}
{% block js_files %}
    {% jquery_confirm 'js' %}
    {% toastr 'js' %}
{% endblock %}
{% block js_code %}
<script type="text/javascript">
{% if messages %}
toastr.success("{% for message in messages %}{{ message }}{% endfor %}", '操作提示');
{% endif %}
$(function(){
    $('a.btn_del').confirm({
        title: '确认!',
            content: '确认要卸载当前 Python 版本吗？(除非版本有问题，否则不建议卸载)',
            buttons: {
                confirm: {
                    text: '确认',
                    action: function (){
                       location.href = this.$target.attr('href');
                    }
                },
        cancel:{
            text: '取消',
        },
        }
    });

})
</script>
{% endblock %}

{% block pagecontent %}
<div class="row">
    <div class="col-12">
        <a href="{% url 'devpython:install' %}" class="btn btn-outline-success mb-2 float-right">安装其他版本</a>
    </div>
</div>
<div class="card card-gray">
    <div class="card-header">
        <h3 class="card-title">已安装的 Python 版本</h3>
    </div>
    <div class="card-body">
        <table class="table table-bordered table-hover table-sm">
            <thead class="thead-light">
            <tr><th>版本名称</th><th>类型</th><th>来源版本</th><th></th></tr>
            </thead>
            <tbody>
{% for py, envs in pylist.items %}
            <tr>
                <td>{{ py }}</td><td>基础</td><td></td>
                <td>
            {% if not envs %}
                <a href="{% url 'devpython:del' py %}" class="btn btn-link btn-xs text-danger btn_del">删除</a>
            {% endif %}
                </td>
            </tr>
    {% for env in envs %}
            <tr>
                <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ env }}</td>
                <td>虚拟</td>
                <td>{{ py }}</td>
                <td></td>
            </tr>
    {% endfor %}
{% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

apps/devpython/templates/devpython/python_install.html
{% extends 'layout/layout_main.html' %}
{% load frame_html %}
{% load frame_plugins %}

{% block css_files %}
    {% jquery_validation_engine 'css' %}
    {% select2 'css' %}
{% endblock %}
{% block js_files %}
    {% jquery_validation_engine 'js' %}
    {% select2 'js' %}
{% endblock %}
{% block js_code %}
<script type="text/javascript">
$(document).ready(function(){
    {% select2 'jscode' %}
    {% jquery_validation_engine 'jsconde' form_id='form' %}
})

    {#function checkfile() {#}
    {#    if ($('#id_version').val() != '') {#}
    {#        $('#card-footer').html('');#}
    {#        $('#card-footer').append(#}
    {#            '<button type="button" class="btn btn-info" id="btn_download" onclick="download();">下载安装文件</button>'#}
    {#        );#}
    {#    }else{#}
    {#        alert('请选择内容！');#}
    {#    }#}
    {# } #}

{#    function download(){#}
{#        $('#showprocess').html('');#}
{#        $('#runinfo').html('').append('<p>开始下载Python编译文件。。。。</p><p>' +#}
{#            '<i class="fas fa-3x fa-sync-alt fa-spin" id="load"></i></p>');#}
{#        $.ajax({#}
{#            type: 'POST',#}
{#            dataType: "json",#}
{#            url: '{% url 'devpython:install_download' %}',#}
{#            data: $('#form').serialize(),#}
{#            success: function(result){#}
{#                if (result.run_end == '0'){#}
{#                    $('#runinfo').html('');#}
{#                    $('#card-footer').html('');#}
{#                    $('#runinfo').append('<p>下载完成！可以尝试开始安装~</p>');#}
{#                    $('#card-footer').append(#}
{#'<button type="button" class="btn btn-info ml-2" id="btn_run" onclick="runsetup();">开始编译安装（需要时间很长，请勿刷新）</button>'#}
{#                    );#}
{#                }else{#}
{#                    $('#load').remove();#}
{#                    $('#runinfo').append('<p>下载失败。。。</p>');#}
{#                }#}
{#                $('#showprocess').html(result.showprocess);#}
{#            },#}
{#            error: function (){#}
{#                 ('#runinfo').html('');#}
{#                $('#runinfo').append('<p>提交检查有故障!~</p>');#}
{#            }#}
{#        })#}
{#    }#}

    function runsetup(){
        $('#runinfo').html('');
        $('#showprocess').html('');
        $('#runinfo').append('<p>开始编译安装，时间较长，请勿刷新，等待自行跳转。。。。</p><p>' +
            '<i class="fas fa-3x fa-sync-alt fa-spin"></i></p>');
        $.ajax({
            type: 'POST',
            dataType: "json",
            url: '{% url 'devpython:install_run' %}',
            data: $('#form').serialize(),
            success: function(result){
                if (result.run_end == '0'){
                    $(location).attr('href', "{% url 'devpython:index' %}");
                }else{
                    $('#runinfo').html('');
                    $('#runinfo').append('<p>安装失败,请检查。。。</p>');
                    $('#showprocess').html(result.showprocess);
                }
            },
            error: function (){
                $('#runinfo').html('');
                $('#runinfo').append('<p>提交有故障!~</p>');
             }
        })
    }

</script>
{% endblock  %}

{% block pagecontent %}
<div class="card">
<form id="form" name="form" method="post" class="form-horizontal">
    {% csrf_token %}
<div class="card-body">
    <div class="form-group row">
        <label class="col-sm-2 col-form-label">{{ form.version.label }}</label>
         <div class="col-sm-10">
             <select id="id_version" name="version" class="form-control select2 validate[required]"
                     data-errormessage-value-missing="请选择要安装的版本">
             <option value="">请选择...</option>
    {% for py in py_version_list %}
    <option value="{{ py }}">{{ py }}</option>
    {% endfor %}
             </select>
         </div>
    </div>

{#    <div class="form-group row">#}
{#        <label class="col-sm-2 col-form-label">{{ form.website.label }}</label>#}
{#        <div class="col-sm-10">{{ form.website }}</div>#}
{#    </div>#}
    <div id="runinfo">
<button type="button" class="btn btn-info ml-2" id="btn_run" onclick="runsetup();">开始编译安装（需要时间很长，请勿刷新）</button>
    </div>
</div>
    <div class="card-footer" id="card-footer"> </div>
</form>
</div>
<div style="overflow:auto;width:100%;height:300px;background:#000000;color:#FFFFFF;padding:5px;" id="showprocess">

</div>
{% endblock %}