appcommon/urls.py
from django.urls import path, include
from django.contrib.auth.decorators import login_required

from . import views

app_name = 'site_home'

urlpatterns = [
    path('index/', login_required(views.SiteHomeView.as_view()), name='index'),
    path('shutdown/<str:action>', login_required(views.Shutdown.as_view()), name='shutdown'),
    path('hostname/', login_required(views.HostnameView.as_view()), name='hostname'),

]

conf/urls.py
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


from appcommon import views
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('', views.CosyLoginView.as_view()),
    path('login/', views.CosyLoginView.as_view(), name='site_login'),
    path('logout/', login_required(views.CosyLayoutView.as_view()), name='site_logout'),
    path('home/', include('appcommon.urls', namespace='site_home')),
    path('system/', include('apps.system.urls', namespace='system')),
    path('devpython/', include('apps.devpython.urls', namespace='devpython')),

]

urlpatterns += staticfiles_urlpatterns()

appcommon/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class Users(AbstractUser):

    name = models.CharField(verbose_name='姓名', max_length=100, blank=True)
    email = models.EmailField(verbose_name="邮箱地址", unique=True)
    description = models.TextField(verbose_name="备注", blank=True)

    first_name = None
    last_name = None

    class Meta:
        swappable = 'AUTH_USER_MODEL'
        default_permissions = ()
        verbose_name = verbose_name_plural = '用户'

appcommon/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UsernameField
from django.core.exceptions import ValidationError

class FormBase(forms.Form):
    """
    基础表单 不使用表单生成HTML5验证
    """
    use_required_attribute = False


class LoginForm(AuthenticationForm, FormBase):
    """登录表单"""
    username = UsernameField(
        error_messages={'required': '请输入登录用户名！'},
        widget=forms.TextInput(
            attrs={'autofocus': True, 'class': 'form-control validate[required]', 'autocomplete': 'username',
                   'placeholder': '用户名', 'data-errormessage-value-missing': '请输入用户名！'}
        )
    )
    password = forms.CharField(
        error_messages={'required': '请输入登录密码！'},
        widget=forms.PasswordInput(attrs={'autocomplete': 'current-password',
                                          'class': 'form-control validate[required]', 'placeholder': '密码',
                                          'data-errormessage-value-missing': '请输入密码！'}
                                   ),
    )


class HostnameForm(FormBase):
    """ 修改当前主机名表单 """
    hostname = forms.CharField(label="主机名", widget=forms.TextInput(
        attrs={'class': 'form-control validate[required]'}
    ))

    def clean_hostname(self):
        data = self.cleaned_data['hostname']
        if not data:
            raise ValidationError("必须要指定主机名称！")
        return data


class ShutdownForm(FormBase):
    delay = forms.ChoiceField(
        label="延迟时间",
        choices=(('now', '立即'), ('1', '1分钟'), ('5', '5分钟'), ('20', '20分钟'), ('40', '40分钟'), ('60', '60分钟')),
        widget=forms.Select(attrs={'class': 'form-control'})
    )

appcommon/views.py
import subprocess
import datetime
import platform
import psutil
import os

from django.views.generic.edit import FormView
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic.base import TemplateView
from django.urls import reverse_lazy

from .forms import LoginForm
from .forms import ShutdownForm, HostnameForm


class CosyLoginView(LoginView):
    """登录"""
    form_class = LoginForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = '登录'
        return context


class CosyLayoutView(LogoutView):
    """注销登录"""
    pass


class SiteHomeView(TemplateView):
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['parent_menu'] = 'home'
        context['page_title'] = '系统仪表板'
        context['os'] = subprocess.run('cat /etc/redhat-release', shell=True, capture_output=True,
                                       encoding='utf-8').stdout.strip()
        context['current_time'] = subprocess.run('date', shell=True, capture_output=True,
                                                 encoding='utf-8').stdout.strip()
        context['platform'] = platform.platform()
        context['machine'] = platform.machine()
        context['cpu'] = subprocess.run(['cat', '/proc/cpuinfo'], stdout=subprocess.PIPE, encoding="utf-8")\
            .stdout.split('\t')[6].lstrip(': ').rstrip('stepping')
        context['cpu_count'] = psutil.cpu_count()

        return context


class Shutdown(FormView):
    template_name = 'shutdown.html'
    form_class = ShutdownForm
    success_url = reverse_lazy('site_home:index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['parent_menu'] = 'home'
        context['page_title'] = ''
        context['help_text'] = ''
        get_action = self.kwargs.get('action')
        if get_action == 'r':
            context['page_title'] = '重启'
            context['help_text'] = '<h5>注意</h5>' \
                                   '<p>提交后将执行重新启动系统。当前所有登录用户将被中断连接，所有服务将被重新启动。</p>' \
                                   '<p>将使用 shutdown -r 命令重启</p><p>重启后切勿重复提交本页！</p>'
        if get_action == 'h':
            context['page_title'] = '关机'
            context['help_text'] = '<h5>注意</h5>' \
                                   '<p>提交后将执行关闭系统。所有服务将被停止，所有用户将被中断连接，电源也会关闭(如果您的硬件支持的话)</p>' \
                                   '<p>将使用 shutdown -h 命令关机</p><p>重启后切勿重复提交本页！</p>'
        return context

    def form_valid(self, form):
        get_commander = 'shutdown -%s %s' % (self.kwargs.get('action'), form.cleaned_data['delay'])
        os.system(get_commander)
        return super().form_valid(form)


class HostnameView(FormView):
    form_class = HostnameForm
    template_name = 'hostname.html'
    success_url = reverse_lazy('site_home:index')

    def get_initial(self):
        self.initial['hostname'] = subprocess.run('hostname', shell=True, capture_output=True,
                                                  encoding="utf-8").stdout.strip("\n")
        return self.initial.copy()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['parent_menu'] = 'home'
        context['page_title'] = '配置主机名'
        context['breadcrumb'] = [
            {'title': '仪表板', 'href': reverse_lazy('site_home:index'), 'active': False},
            {'title': '配置主机名', 'href': '', 'active': True},
        ]
        return context

    def form_valid(self, form):
        hostname = form.cleaned_data['hostname']
        subprocess.run('hostnamectl set-hostname ' + hostname, shell=True, capture_output=True,
                       encoding="utf-8")
        return super().form_valid(form)

appcommon/templates/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

appcommon/templates/home.html
{% extends 'layout/layout_main.html' %}
{% load frame_helper %}
{% load frame_get %}

{% block pagecontent %}
<div class="row">
    <div class="card">
        <div class="card-body">
                <div class="row">
                    <dt class="col-sm-3">主机名</dt>
                    <dd class="col-sm-9"><a href="{% url 'site_home:hostname' %}">{% get_hostname %}</a></dd>
                    <dt class="col-sm-3">操作系统</dt>
                    <dd class="col-sm-9">{{ os }}</dd>
                    <dt class="col-sm-3">系统时间</dt>
                    <dd class="col-sm-9">{{ current_time }}</dd>
                    <dt class="col-sm-3">内核架构</dt>
                    <dd class="col-sm-9">{{ platform }} 运行于 {{ machine }}</dd>
                    <dt class="col-sm-3">CPU</dt>
                    <dd class="col-sm-9">{{ cpu }}, {{ cpu_count }}核</dd>

                    <dt class="col-sm-3">电源操作</dt>
                    <dd class="col-sm-9">
                        <div class="col-sm-6">
                            <div class="input-group-prepend">
                            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                              选择操作
                            </button>
                            <div class="dropdown-menu" style="">
                              <a class="dropdown-item" href="{% url 'site_home:shutdown' 'r' %}">重启</a>
                              <a class="dropdown-item" href="{% url 'site_home:shutdown' 'h' %}">关机</a>
                            </div>
                          </div>
                        </div>
                    </dd>
                </div>
        </div>
    </div>
</div>
{% endblock %}

appcommon/templates/hostname.html
{% extends 'layout/layout_main.html' %}
{% load frame_html %}
{% load frame_plugins %}

{% block css_files %}
    {% jquery_validation_engine 'css' %}
{% endblock %}

{% block js_files %}
    {% jquery_validation_engine 'js' %}
{% endblock %}

{% block js_code %}
<script type="text/javascript">
$(function(){
    {% jquery_validation_engine 'jscode' form_id='form' %}
})
</script>
{% endblock %}


{% block pagecontent %}
<div class="card">{% csrf_token %}
<form name="form" id="form" method="post">{% csrf_token %}
    <div class="card-body">
        <div class="form-group">
            {{ form.hostname.label_tag  }}
            {{ form.hostname }}
          </div>
    </div>
    <div class="card-footer">
        {% form_btn 'submit' %}{% form_btn 'reset' %}
    </div>
 </form>
</div>
{% endblock %}

appcommon/templates/shutdown.html
{% extends 'layout/layout_main.html' %}
{% load frame_html %}

{% block pagecontent %}
<div class="callout callout-danger">{{ help_text|safe }}</div>
    <div class="card">
    <form name="form" method="post" class="form-horizontal">
        <div class="card-body">
{% if form.errors %}
<div class="alert alert-warning alert-dismissible">
     <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
     <h5><i class="icon fas fa-exclamation-triangle"></i> 提交错误!</h5>
    {% for error,value in form.errors.items %}
        {% for error_value in value %}
        <p><strong>{{ error_value|escape }}</strong></p>
            {% endfor %}
    {% endfor %}
</div>
{% endif %}
                {% csrf_token %}
                {% for field in form %}
                <div class="form-group row">
                    <label for="{{ field.id_for_label }}" class="col-sm-2 col-form-label">{{ field.label }}</label>
                    <div class="col-sm-10">
                        {{ field }}
                    </div>
                  </div>
                {% endfor %}
        </div>
        <div class="card-footer">
            {% form_btn 'submit' %}
        </div>
    </form>
    </div>

{% endblock %}