apps/system/urls.py
from django.urls import path, include
# from . import view_xterm

app_name = 'system'

urlpatterns = [
    path('firewalld/', include('apps.system.urls_firewalld', namespace='firewalld')),
    path('network/', include('apps.system.urls_network', namespace='network')),
    path('process/', include('apps.system.urls_process', namespace='process')),
    # path('terminal/', view_xterm.index, name='terminal'),
    path('sysfiles/', include('apps.system.urls_sysfiles', namespace='sysfiles')),
    path('usersadmin/', include('apps.system.urls_usersadmin', namespace='usersadmin')),
    path('timezone/', include('apps.system.urls_timezone', namespace='timezone')),
]

conf/urls.py
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


from appcommon import views
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('', views.CosyLoginView.as_view()),
    path('login/', views.CosyLoginView.as_view(), name='site_login'),
    path('logout/', login_required(views.CosyLayoutView.as_view()), name='site_logout'),
    path('home/', include('appcommon.urls', namespace='site_home')),
    path('system/', include('apps.system.urls', namespace='system')),
    path('devpython/', include('apps.devpython.urls', namespace='devpython')),

]

urlpatterns += staticfiles_urlpatterns()

apps/system/models.py
from django.db import models

# Create your models here.

apps/system/forms.py
from django import forms
from appcommon.forms import FormBase
from django.core.validators import validate_slug
from django.core.exceptions import ValidationError


class FirewallPortForm(FormBase):
    """ 增加防火墙端口 表单"""
    zone = forms.CharField(widget=forms.HiddenInput())
    port_type = forms.CharField(required=True)
    port_only = forms.IntegerField(required=False, widget=forms.TextInput(attrs={'class': 'form-control'}))
    port_start = forms.IntegerField(required=False, widget=forms.TextInput(attrs={'class': 'form-control'}))
    port_end = forms.IntegerField(required=False, widget=forms.TextInput(attrs={'class': 'form-control'}))
    proto = forms.CharField(
        widget=forms.Select(attrs={'class': 'form-control'}, choices=(('tcp', 'tcp'), ('udp', 'udp')))
    )

    def clean_port_type(self):
        data = self.cleaned_data["port_type"]
        if not data:
            raise ValidationError("必须要指定端口提交类型！")
        return data

    def clean(self):
        """ 验证字段内容 """
        cleaned_data = super().clean()
        port_type = cleaned_data.get('port_type')
        port_only = cleaned_data.get('port_only')
        port_start = cleaned_data.get('port_start')
        port_end = cleaned_data.get('port_end')
        proto = cleaned_data.get('proto')

        if (port_type == '1') and (not port_only):
            self.add_error('port_only', '端口号不能为空！')
        if (port_type == '2') and ((not port_start) or (not port_end)):
            self.add_error('port_end', '起始端口号和终止端口号必须同时存在！')

        if proto is None:
            self.add_error('proto', '必须指定端口网络协议！')


class FirewallServiceForm(FormBase):
    """ 所加防火墙允许服务 """
    zone = forms.CharField(widget=forms.HiddenInput())
    service = forms.CharField()


class ConnRenameForm(FormBase):
    """ 网络连接更名表单 """
    newname = forms.CharField(error_messages={"required": "新连接名称不能为空！"},
        required=True, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': '请输入新名称'})
    )


class ConnForm(FormBase):
    """ 网络连接配置表单 """
    name = forms.CharField(
        label="连接名称", error_messages={"required": '连接名称不能为空！'}, required=True,
        validators=[validate_slug],
        widget=forms.TextInput(attrs={
            'class': 'form-control validate[required,custom[onlyLetterNumber],ajax[ajaxName]]',
            'data-errormessage-value-missing': '* 连接名称不能为空！',
            'data-errormessage-custom-error': '* 只能输入英文和数字!'
        })
    )
    autoconnect = forms.CharField(
        label='自动连接',
        widget=forms.CheckboxInput(
            attrs={'data-bootstrap-switch': ''}
        )
    )
    mtu = forms.IntegerField(
        label="MTU", required=False,
        widget=forms.TextInput(attrs={'class': 'form-control validate[custom[integer]]', 'placeholder': '自动'})
    )
    ipv4method = forms.CharField(
        label='IPv4模式',
        widget=forms.Select(
            choices=(('auto', '自动'), ('manual', '手动')),
            attrs={'class': 'form-control'}
        )
    )
    ip4 = forms.CharField(
        label='IPv4地址', required=False,
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )
    gw4 = forms.CharField(label='网关', required=False, widget=forms.TextInput(attrs={'class': 'form-control'}))
    ip4dns = forms.CharField(label='DNS', required=False, widget=forms.TextInput(attrs={'class': 'form-control'}))


class FileEditForm(FormBase):
    path = forms.CharField(widget=forms.HiddenInput())
    filename = forms.CharField(label='文件名',  widget=forms.TextInput(attrs={
            'class': 'validate[required]',
            'data-errormessage-value-missing': '* 文件名不能为空！',
        })
    )
    filecontent = forms.CharField(required=False, widget=forms.Textarea)


class FileDirForm(FormBase):
    path = forms.CharField(widget=forms.HiddenInput)
    name = forms.CharField(label='名称', error_messages={"required": '名称不能为空！'}, required=True,
        widget=forms.TextInput(attrs={
            'class': 'form-control validate[required]',
            'data-errormessage-value-missing': '* 名称不能为空！',
        })
    )


class FileUploadForm(FormBase):
    path = forms.CharField(
        label='上传到目录：', error_messages={"required": '上传目录不能为空！'}, required=True,
        widget=forms.TextInput(attrs={
            'class': 'form-control validate[required]',
            'data-errormessage-value-missing': '* 名称不能为空！',
        })
    )
    fileupload = forms.FileField(
        required=True, error_messages={"required": '上传文件不能为空！'},
        widget=forms.FileInput(attrs={
            'class': 'form-control validate[required]',
            'data-errormessage-value-missing': '* 上传文件必须要选择！',
        }))


class FileDownloadForm(FormBase):
    path = forms.CharField(widget=forms.HiddenInput)
    url = forms.CharField(
        error_messages={"required": '下载URL地址不能为空！'}, required=True,
        label='下载文件的URL', widget=forms.TextInput(attrs={
            'class': 'form-control validate[required]',
            'data-errormessage-value-missing': '* 下载URL地址不能为空！',
        })
    )


class UserAddForm(FormBase):
    real_name = forms.CharField(label='全名*', required=True, widget=forms.TextInput(attrs={
            'class': 'form-control validate[required]',
            'data-errormessage-value-missing': '* 全名不能为空！',
        }))
    user_name = forms.CharField(label='用户名*', required=True, widget=forms.TextInput(attrs={
            'class': 'form-control validate[required]',
            'data-errormessage-value-missing': '* 用户名不能为空！',
        }))
    pw1 = forms.CharField(label='密码*', required=True, widget=forms.PasswordInput(attrs={
            'class': 'form-control validate[required, minSize[8]]',
            'data-errormessage-value-missing': '* 密码不能为空！',
        }))
    pw2 = forms.CharField(label='密码确认*', required=True, widget=forms.PasswordInput(attrs={
            'class': 'form-control validate[required, equals[id_pw1]]',
            'data-errormessage-value-missing': '* 确定不能为空！',
        }))


class SystemUserForm(FormBase):
    real_name = forms.CharField(label='全名*', required=True, widget=forms.TextInput(attrs={
            'class': 'form-control col-sm-4 validate[required]',
            'data-errormessage-value-missing': '* 全名不能为空！',
    }))
    is_admin = forms.BooleanField(label='角色', required=False)
    is_locked = forms.BooleanField(label='锁定帐号', required=False)


class SystemUserDelForm(FormBase):
    del_home = forms.BooleanField(label='同时删除用户主目录数据', required=False)


class SystemUserPwdForm(FormBase):
    pw1 = forms.CharField(label='密码*', required=True, widget=forms.PasswordInput(attrs={
            'class': 'form-control validate[required, minSize[8]]',
            'data-errormessage-value-missing': '* 密码不能为空！',
        }))
    pw2 = forms.CharField(label='密码确认*', required=True, widget=forms.PasswordInput(attrs={
            'class': 'form-control validate[required, equals[id_pw1]]',
            'data-errormessage-value-missing': '* 确定不能为空！',
        }))


class TimezoneForm(FormBase):
    zone = forms.CharField(label='时区')
    time_sync = forms.IntegerField()
    # time_set = forms.ChoiceField(label='手动指定')
    set_date = forms.DateField(widget=forms.HiddenInput())
    hour = forms.IntegerField(min_value=0, max_value=23)
    minute = forms.IntegerField(min_value=0, max_value=60)
    second = forms.IntegerField(min_value=0, max_value=60)



apps/system/templates/system/files_edit.html
{% extends 'layout/layout_main.html' %}
{% load static %}
{% load frame_plugins %}

{% block css_files %}
    {% codemirror 'css' %}
    {% jquery_validation_engine 'css' %}
{% endblock %}

{% block js_files %}
    {% codemirror 'js' %}
    {% jquery_validation_engine 'js' %}
{% endblock %}

{% block js_code %}
<script>
 {% jquery_validation_engine 'jscode' form_id='form' %}

CodeMirror.modeURL = "{% static 'plugins/codemirror/mode' %}/%N/%N.js";
var editor = CodeMirror.fromTextArea(document.getElementById("id_filecontent"), {
    lineNumbers: true,
    theme: 'monokai',
});
var modeInput = "{{ filename }}";
  var val = modeInput, m, mode, spec;
  if (m = /.+\.([^.]+)$/.exec(val)) {
    var info = CodeMirror.findModeByExtension(m[1]);
    if (info) {
      mode = info.mode;
      spec = info.mime;
    }
  } else if (/\//.test(val)) {
    var info = CodeMirror.findModeByMIME(val);
    if (info) {
      mode = info.mode;
      spec = val;
    }
  } else {
    mode = spec = val;
  }
  if (mode) {
    editor.setOption("mode", mode);
    CodeMirror.autoLoadMode(editor, mode);
  } else {
    console.log("Could not find a mode corresponding to " + val);
  }

</script>
{% endblock %}

{% block pagecontent %}
<div class="col-md-12">
{% if check %}
<form id="form" name="form" method="post">{% csrf_token %}
      <div class="card card-outline card-info">
        <div class="card-header">
          <h3 class="card-title">
            <i class="fas fa-edit"></i> {{ path }}{{ form.filename }}
          </h3>
            <div class="card-tools">
                <button type="submit" class="btn btn-tool"><i class="fa fa-save"></i></button>
                <button type="button" class="btn btn-tool" data-card-widget="maximize">
                    <i class="fas fa-expand"></i>
                  </button>
                <button type="button" class="btn btn-tool">
                   <a href="{% url 'system:sysfiles:list' %}?path={{ path }}"><i class="fas fa-times"></i></a>
                  </button>
            </div>
        </div>
     {{ form.path }}
    <div class="card-body p-0">
        {{ form.filecontent }}
    </div>
      </div>
</form>
{% else %}
<div class="alert alert-warning alert-dismissible">
  <a href="{% url 'system:sysfiles:list' %}?path={{ path }}" class="close" >×</a>
<h5><i class="icon fas fa-exclamation-triangle"></i> 文件类型不支持在线编辑!</h5>
</div>

{% endif %}
</div>
{% endblock %}

apps/system/templates/system/files_upload.html
{% extends 'layout/layout_main.html' %}
{% load static %}
{% load frame_html %}

{% block pagecontent %}
<form id="form" name="form" method="post" enctype="multipart/form-data">{% csrf_token %}
      <div class="card">
          <div class="card-header">
              {{ form.path.label }}{{ form.path }}
    {% if form.path.errors %}
          <span class="text-danger">{% for error in form.path.errors %}{{ error }}{% endfor %}</span>
    {% endif %}
          </div>
    <div class="card-body">
        {{ form.fileupload }}
{% if form.fileupload.errors %}
      <span class="text-danger">{% for error in form.fileupload.errors %}{{ error }}{% endfor %}</span>
{% endif %}
    </div>
          <div class="card-footer">{% form_btn 'submit' %}</div>
      </div>
</form>
{% endblock %}


apps/system/templates/system/firewalld.html
{% extends 'layout/layout_main.html' %}
{% load frame_html %}

{% block pagecontent %}
<div class="card">
    <div class="card-body">
        <dl class="row">
          <dt class="col-sm-1">服务名</dt>
          <dd class="col-sm-11">{{ service }}</dd>
          <dt class="col-sm-1">路径</dt>
          <dd class="col-sm-11">{{ loaded }}</dd>
          <dt class="col-sm-1">状态</dt>
          <dd class="col-sm-11">
              {% if statue_str == 'no' %}<span class="text-danger">停止</span>{% endif %}
              {% if statue_str == 'yes' %}<span class="text-success">运行</span>{% endif %}
                <button type="button" class="btn btn-default dropdown-toggle ml-2" data-toggle="dropdown" aria-expanded="false">
                  选择操作
                </button>
                <div class="dropdown-menu" >
                    {% if statue_str == 'no' %}<a href="{% url 'system:firewalld:action' %}?action=start" class="dropdown-item">启动</a>{% endif %}
                    {% if statue_str == 'yes' %}<a href="{% url 'system:firewalld:action' %}?action=stop" class="dropdown-item">停止</a>{% endif %}
                    <a href="{% url 'system:firewalld:action' %}?action=restart" class="dropdown-item">重启</a>
                    <a href="{% url 'system:firewalld:action' %}?action=reload" class="dropdown-item">重载</a>
                </div>
          </dd>
          <dt class="col-sm-1">开机启动</dt>
          <dd class="col-sm-11">
              {% if boot == 'enabled' %}<span class="text-success">启用</span>{% endif %}
              {% if boot == 'disabled' %}<span class="text-danger">禁用</span>{% endif %}
                <button type="button" class="btn btn-default dropdown-toggle ml-2" data-toggle="dropdown" aria-expanded="false">
                  选择操作
                </button>
                <div class="dropdown-menu" >
                {% if boot == 'enabled' %}<a href="{% url 'system:firewalld:action' %}?action=disabled" class="dropdown-item">禁用</a>{% endif %}
                {% if boot == 'disabled' %}<a href="{% url 'system:firewalld:action' %}?action=enabled" class="dropdown-item">启用</a>{% endif %}
                </div>
          </dd>
        </dl>

{% if statue_str == 'yes' %}
    <a href="{% url 'system:firewalld:port' %}" class="btn btn-success">防火墙配置</a>
{% endif %}

    </div>
</div>
{% endblock %}

apps/system/templates/system/firewalld_port.html
{% extends 'layout/layout_main.html' %}
{% load frame_html %}
{% load frame_plugins %}

{% block css_files %}
    {% jquery_confirm 'css' %}
    {% toastr 'css' %}
{% endblock %}
{% block js_files %}
    {% jquery_confirm 'js' %}
    {% toastr 'js' %}
{% endblock %}
{% block js_code %}
<script type="text/javascript">
{% if messages %}
toastr.success("{% for message in messages %}{{ message }}{% endfor %}", '操作提示');
{% endif %}
$(function(){
    $('.btn_del').on('click', function(){
        let formName = $(this).closest("form").attr("name");
        $.confirm({
            title: '确认!',
            content: '确认要删除当前端口吗？',
            buttons: {
                confirm: {
                    text: '确认',
                    action: function (){
                        $('#' + formName).submit();
                    }
                },
                cancel:{
                    text: '取消',
                },
            }
        });
    });
})
</script>
{% endblock %}

{% block pagecontent %}
<div class="row">
{% include 'system/firewalld_zones_list.html' %}
<div class="col-md-10">
    <div class="card card-gray card-tabs">
        <div class="card-header p-0 pt-1">
            <ul class="nav nav-tabs"  role="tablist">
  <li class="nav-item">
      <a class="nav-link active" href="{% url 'system:firewalld:port' %}?zone={{ currentZone }}" >端口</a>
  </li>
  <li class="nav-item">
      <a class="nav-link" href="{% url 'system:firewalld:service' %}?zone={{ currentZone }}" >服务</a>
  </li>
</ul>

          </div>
        <div class="card-body">
<a class="btn btn-outline-success margin_right_10" href="{% url 'system:firewalld:reload' %}?from=port&zone={{ currentZone }}">
    <i class="fa fa-sync"></i> 重载防火墙规则
</a>
<a class="btn btn-outline-success margin_right_10" href="{% url 'system:firewalld:port_add' %}?zone={{ currentZone }}">
    <i class="fa fa-plus"></i> 添加端口
</a>
            <table class="table table-bordered table-hover table-sm mt-2">
                  <thead class="thead-light">
                    <tr>
                      <th>端口号</th>
                      <th>协议</th>
                      <th></th>
                    </tr>
                  </thead>
                  <tbody>
                  {% for port in ports %}
                    <tr>
                      <td>{{ port.port }}</td>
                      <td>{{ port.protocol }}</td>
                      <td>
        {% if port.port == '8000' and port.protocol == 'tcp' %}-{% else %}
            <form id="form_port_{{ current_zone }}_{{ port.port }}" name="form_port_{{ current_zone }}_{{ port.port }}" action="{% url 'system:firewalld:port_del' %}"
                  method="post">
            {% csrf_token %}
                <input type="hidden" id="id_zone" name="zone" value="{{ currentZone }}" />
                <input type="hidden" id="'id_port" name="port" value="{{ port.port }}" />
                <input type="hidden" id="'id_protocol" name="protocol" value="{{ port.protocol }}" />
                <button type="button" class="btn btn-link btn-xs text-danger btn_del">删除</button>
            </form>
        {% endif %}
                      </td>
                    </tr>
                  {% endfor %}
                  </tbody>
                </table>
        </div>
    </div>

</div>
</div>
{% endblock %}

apps/system/templates/system/firewalld_service_add.html
{% extends 'layout/layout_main.html' %}
{% load frame_html %}
{% load frame_plugins %}

{% block css_files %}
    {% jquery_validation_engine 'css' %}
    {% select2 'css' %}
{% endblock %}
{% block js_files %}
    {% jquery_validation_engine 'js' %}
    {% select2 'js' %}
{% endblock %}

{% block js_code %}
<script type="text/javascript">
$(document).ready(function(){
    {% select2 'jscode' %}
    {% jquery_validation_engine 'jscode' form_id='form' %}
})
</script>
{% endblock  %}

{% block pagecontent %}
    {% if messages %}
<div class="alert alert-warning alert-dismissible">
<button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
<h5><i class="icon fas fa-exclamation-triangle"></i>执行错误</h5>
    {% for message in messages %}{{ message }}{% endfor %}
</div>
    {% endif %}

<div class="card">
    <form id="form" name="form" method="post" class="form-horizontal">
        {% csrf_token %}{{ form.zone }}
        <div class="card-body">
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">区域</label>
                <div class="col-sm-10">{{ form.zone.value }}</div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">服务</label>
                <div class="col-sm-10">
<select class="select2 validate[required]" name="service" id="id_service" data-errormessage-value-missing="请选择要添加的服务">
    <option value="">请选择服务...</option>
    {% for key, value in services.items %}
        <option value="{{ key }}">
            {{ value.short }}
            （TCP:{{ value.tcp|join:", " }}   UDP:{{ vlaue.udp|join:", " }}）
        </option>
    {% endfor %}
</select>
                </div>
            </div>

        </div>
        <div class="card-footer">
            <button type="submit" class="btn bg-success">添加服务</button>
        </div>
    </form>
</div>
{% endblock %}

apps/system/templates/system/network_conn_add.html
{% extends 'layout/layout_main.html' %}
{% load frame_html %}
{% load frame_plugins %}
{% load frame_helper %}

{% block css_files %}
    {% jquery_validation_engine 'css' %}
{% endblock %}

{% block js_files %}
    {% bootstrap_switch %}
    {% jquery_validation_engine 'js' %}
{% endblock %}

{% block js_code %}
<script type="text/javascript">
$(function () {

    $("input[data-bootstrap-switch]").each(function(){
      $(this).bootstrapSwitch({
          onText: '开',
          offText: '关',
          state: $(this).prop('checked'),
          onColor: 'success',
          offColor: 'danger',
      })
    })
    $.validationEngineLanguage.allRules["ajaxName"] = {
          'url': '{% url 'system:network:conn_check_name' %}',
          'alertTextOk': '此名称可用',
          'alertText': '存在同样的名称！请重新选择名称！',
          'alertTextLoad': '正在验证中...'
    }
    {% jquery_validation_engine 'jscode' form_id='form' %}

})
</script>
{% endblock %}

{% block pagecontent %}
<div class="card card-yellow card-outline card-outline-tabs">
    <div class="card-header">
        <h3 class="card-title"> {{ device_name }} - 新配置 </h3>
    </div>
    <div class="card-header p-0 border-bottom-0">
        <ul class="nav nav-tabs" id="custom-tabs-four-tab" role="tablist">
          <li class="nav-item">
            <a class="nav-link active" id="custom-tabs-four-home-tab" data-toggle="pill" href="#custom-tabs-four-home" role="tab" aria-controls="custom-tabs-four-home" aria-selected="true">身份</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" id="custom-tabs-four-profile-tab" data-toggle="pill" href="#custom-tabs-four-profile" role="tab" aria-controls="custom-tabs-four-profile" aria-selected="false">IPv4</a>
          </li>
        </ul>
    </div>
    {{ form.errors }}
    <form id="form" name="form" method="post" class="form-horizontal">
    {% csrf_token %}
    <div class="card-body">
        <div class="tab-content" id="custom-tabs-four-tabContent">
          <div class="tab-pane fade show active" id="custom-tabs-four-home" role="tabpanel" aria-labelledby="custom-tabs-four-home-tab">
            <div class="form-group row">
                <label for="{{ form.name.id_for_label  }}" class="col-sm-1 col-form-label">{{ form.name.label }}</label>
                <div class="col-sm-11">{{ form.name }}</div>
            </div>
             <div class="form-group row">
                <label for="{{ form.mtu.id_for_label  }}" class="col-sm-1 col-form-label">{{ form.mtu.label }}</label>
                <div class="col-sm-11">{{ form.mtu }}</div>
            </div>
             <div class="form-group row">
                <label for="{{ form.autoconnect.id_for_label  }}" class="col-sm-1 col-form-label">{{ form.autoconnect.label }}</label>
                <div class="col-sm-11">{{ form.autoconnect }}</div>
            </div>
          </div>
          <div class="tab-pane fade" id="custom-tabs-four-profile" role="tabpanel" aria-labelledby="custom-tabs-four-profile-tab">
            <div class="form-group row">
                <label for="{{ form.ipv4method.id_for_label }}" class="col-sm-1 col-form-label">{{ form.ipv4method.label }}</label>
                <div class="col-sm-11">{{ form.ipv4method }}</div>
            </div>
            <div class="form-group row">
                <label for="{{ form.ip4.id_for_label }}" class="col-sm-1 col-form-label">{{ form.ip4.label }}</label>
                <div class="col-sm-11">{{ form.ip4 }}</div>
            </div>
            <div class="form-group row">
                <label for="{{ form.gw4.id_for_label }}" class="col-sm-1 col-form-label">{{ form.gw4.label }}</label>
                <div class="col-sm-11">{{ form.gw4 }}</div>
            </div>
            <div class="form-group row">
                <label for="{{ form.ip4dns.id_for_label }}" class="col-sm-1 col-form-label">{{ form.ip4dns.label }}</label>
                <div class="col-sm-11">{{ form.ip4dns }}</div>
            </div>
          </div>
        </div>
    </div>
    <div class="card-footer">
        {% form_btn 'submit' %}{% form_btn 'back' %}
    </div>
    </form>
</div>
{% endblock %}

apps/system/templates/system/timezone.html
{% extends 'layout/layout_main.html' %}
{% load frame_html %}
{% load frame_plugins %}
{% load frame_helper %}

{% block css_files %}
    {% jquery_validation_engine 'css' %}
    {% select2 'css' %}
    {% icheck_bootstrap %}
    {% jquery_ui 'css' %}
{% endblock %}

{% block js_files %}
    {% jquery_validation_engine 'js' %}
    {% select2 'js' %}
    {% jquery_ui 'js' %}
{% endblock %}

{% block js_code %}
<script type="text/javascript">
$(document).ready(function(){
    {% select2 'jscode' %}
    {% jquery_validation_engine 'jscode' form_id='form' %}
    $("#datepicker").datepicker({
        changeMonth: true,
        changeYear: true,
        regional: 'zn-CN',
        dateFormat: 'yy-mm-dd',
        altField: "#id_set_date",
        altFormat: "yy-mm-dd",
        defaultDate: '{{ form.set_date.value }}'
    });
    $("#hour").spinner({min: 0,max: 23});
    $("#minute").spinner({min: 0,max: 23});
    $("#second").spinner({min: 0,max: 23});
})
</script>
{% endblock  %}

{% block pagecontent %}
    {% if messages %}
<div class="alert alert-warning alert-dismissible">
<button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
<h5><i class="icon fas fa-exclamation-triangle"></i>执行错误</h5>
    {% for message in messages %}{{ message }}{% endfor %}
</div>
    {% endif %}
<div class="col-md-6">
    <form id="form" name="form" method="post">{% csrf_token %}
        <div class="card">
            <div class="card-body">
                <div class="clearfix">
                    <div class="col-md-4 float-left">时区</div>
                    <div class="col-md-8 float-left">
                        <select id="id_zone" name="zone" class="select2 form-control validate[required]">
{% for zone in zone_list %}
  <option value="{{ zone }}"{% if zone in current_zone %} selected{% endif %}>{{ zone }}</option>
{% endfor %}
                        </select>
                    </div>
                </div>
            <hr/>
                <div class="clearfix">
                    <div class="col-md-4 float-left">设置日期时间：</div>
                    <div class="col-md-8 float-left">
                        <p>{{ time }}</p>
                        <div class="icheck-primary d-inline">
<input type="radio" id="id_time_sync_1" name="time_sync" value="1" {% if time_sync == 'enabled' %} checked{% endif %}
       onclick="document.getElementById('show_set_date').style.display='none';">
                            <label for="id_time_sync_1">自动网络同步</label>
                        </div>
                        <div class="icheck-primary d-inline">
<input type="radio" id="id_time_sync_2" name="time_sync" value="2" {% if time_sync == 'disabled' %} checked{% endif %}
        onclick="document.getElementById('show_set_date').style.display='';">
                            <label for="id_time_sync_2">手动修改</label>
                        </div>
                   </div>
                    </div>
            <div class="row mt-3" id="show_set_date" style="display: {% if time_sync == 'enabled' %}none{% else %}{% endif %};">
<div class="col-md-6">
    <div id="datepicker" class="float-right"></div>{{ form.set_date }}
</div>
<div class="col-md-6" >
    <div class="form-group"><label for="id_hour" class="mr-2">时</label>{{ form.hour }}</div>
    <div class="form-group"><label for="id_minute" class="mr-2">分</label>{{ form.minute }}</div>
    <div class="form-group"><label for="id_second" class="mr-2">秒</label>{{ form.second }}</div>
</div>
            </div>
                </div>

            <div class="card-footer">
                {% form_btn 'submit' %}
            </div>
        </div>
    </form>
</div>
{% endblock %}